#!/usr/bin/env bash
# Configure domain zone so that the subdomain www points to load-balancer IP (lb-01)
# www -->    102967-lb-01   100.24.235.154
# web-01 --> 102967-web-01  34.232.70.178
# web-02 --> 102967-web-02  54.174.206.246 



# Set domain and subdomains
domain="codetones.tech"
subdomains=("www" "lb-01" "web-01" "web-02")

# Define function to get subdomain information
getSubdomainInfo () {
    subdomain=$1
    domain=$2
    expected=$3

    # Get subdomain information using dig command
    info=$(dig +short $subdomain.$domain)

    # Check if subdomain information matches the expected value
    if [ "$info" = "$expected" ]; then
        echo "Your subdomain $subdomain points to your $subdomain server IP"
    else
        echo "Your subdomain $subdomain does not point to your $subdomain server IP"
    fi
}

# Loop through subdomains and get information for each
for subdomain in "${subdomains[@]}"
do
    case $subdomain in
        "www")
            expected="100.24.235.154"
            ;;
        "web-01")
            expected="34.232.70.178"
            ;;
        "web-02")
            expected="54.174.206.246"
            ;;
        *)
            echo "Invalid subdomain: $subdomain"
            ;;
    esac

    getSubdomainInfo $subdomain $domain $expected
done
