#!/usr/bin/env bash
# This script installs and configures nginx to listen on port 80, and prints "Hello World" on the served webpage

sudo apt-get update
sudo apt-get -y install nginx
echo 'Hello World!' > /var/www/html/index.html
service nginx start
