#!/bin/env bash

# Update and install nginx
sudo apt-get update
sudo apt-get -y install nginx

# Create a new location block for /redirect_me
sudo bash -c 'cat > /etc/nginx/sites-available/default' << EOF
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;

    index index.html index.htm index.nginx-debian.html;

    server_name _;

    location / {
        try_files \$uri \$uri/ =404;
    }

    location /redirect_me {
        return 301 https://youtu.be/1hTkp6TVePc;
    }
}
EOF

# Restart nginx
sudo systemctl restart nginx
