#!/usr/bin/env bash

# This script installs and configures Nginx on a machine, and creates two basic HTML files in the web root.

sudo apt-get update
sudo apt-get install -y nginx

echo 'Hello World!' | sudo tee /var/www/html/index.html > /dev/null
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html > /dev/null

sudo systemctl restart nginx
