#!/bin/env bash

# The script Installs Nginx and configures it to add a custom header to its HTTP response
sudo apt update
sudo apt install -y nginx

echo "add_header X-Served-By \$hostname;" | sudo tee -a /etc/nginx/nginx.conf

sudo systemctl restart nginx
