#!/usr/bin/env bash

# Configure new Ubuntu machine to serve as load balancer

# Install load balancer
function install_load_balancer {
    sudo apt-get update
    sudo apt-get -y install haproxy
    sudo systemctl enable haproxy
}

# Configure load balancer
function configure_load_balancer {
    sudo bash -c 'cat > /etc/haproxy/haproxy.cfg <<EOF
frontend web-frontend
    bind *:80
    mode http
    default_backend web-backend

backend web-backend
    mode http
    balance roundrobin
    server web-01 34.232.70.178:80 check
    server web-02 54.174.206.246:80 check
EOF'
}

# Restart load balancer service
function restart_load_balancer {
    sudo systemctl restart haproxy
}

# Main script
function main {
    install_load_balancer
    configure_load_balancer
    restart_load_balancer
}

main
