#!/usr/bin/env bash

# Eunsures Nginx runs and listens  on port 80 of all the server’s active IPv4 IPs



apt-get install -y nginx


rm /etc/nginx/sites-enabled/default


ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

# Restart Nginx service
service nginx restart
