#!/usr/bin/env bash

# The script updates the package lists,
# Installs Nginx,
# Removes the default Nginx configurations,
# Creates a symbolic link for Nginx configuration.

apt-get update


apt-get install -y nginx


rm /etc/nginx/sites-enabled/default


ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

# Restart Nginx service
service nginx restart
