#!/usr/bin/env bash
# Configuring server's nginx for listening to 80 port made  short and sweet.
sed -i "s/8080/80/" /etc/nginx/sites-enabled/default
sudo service nginx restart
kill -9 "$(cat /var/run/nginx.pid)"
